services:
  postgres_db:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=authenticator_server
      - POSTGRES_DB=authenticator_server_production
    networks:
      - internal_network
    ports:
      - 5432:5432
    restart: always
  web:
    build:
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      context: .
      dockerfile: docker/Dockerfile.main
    command: bash -c "./bin/rails db:prepare && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/rails
    environment:
        - DATABASE_USER_NAME=authenticator_server
        - DATABASE_NAME=authenticator_server_production
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - postgres_db
    deploy:
      replicas: 1
    networks:
      - internal_network
    restart: always
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.ngnix
    ports:
      - '3000:3000'
    volumes:
      - ./tmp/sockets:/tmp/sockets
      - ./log:/var/www/rails/log
    networks:
      - internal_network
    depends_on:
      - web
    restart: always
networks:
  internal_network:
volumes:
  postgres:
    name: authenticator_server_data